/**
 * types/database.ts
 *
 * Supabase database type definitions for Aura OS.
 *
 * Hand-authored from DATABASE.md — the source of truth.
 * When the Supabase CLI becomes available, replace this file with:
 *   supabase gen types typescript --project-id <ref> > types/database.ts
 *
 * Do not edit this file manually once CLI generation is in place.
 */

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

export type MissionStatus =
  | "IDEA"
  | "PLANNING"
  | "APPROVAL"
  | "EXECUTION"
  | "ON_HOLD"
  | "REVIEW"
  | "COMPLETED"
  | "CANCELLED";

export type EmployeeStatus = "ACTIVE" | "IDLE" | "ON_MISSION" | "INACTIVE";

export type KnowledgeLayer = "COMPANY" | "PROJECT" | "EMPLOYEE";

export type AssignmentTargetType = "MANAGER" | "EMPLOYEE";

export type NotificationType =
  | "SYSTEM"
  | "INFO"
  | "SUCCESS"
  | "WARNING"
  | "ERROR"
  | "AI"
  | "AUTOMATION";

export type NotificationActor =
  | "SYSTEM"
  | "OWNER"
  | "MANAGER"
  | "EMPLOYEE"
  | "AI";

export type NotificationEntityType =
  | "MISSION"
  | "MANAGER"
  | "EMPLOYEE"
  | "KNOWLEDGE"
  | "ARTIFACT";

// ---------------------------------------------------------------------------
// Row types — shape of a row returned from Supabase
// ---------------------------------------------------------------------------

export interface ProfileRow {
  id: string;          // uuid — matches auth.users(id)
  full_name: string;
  email: string;
  created_at: string;  // timestamptz returned as ISO string
  updated_at: string;
}

export interface ManagerRow {
  id: string;
  name: string;
  email: string;
  department: string;
  owner_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface EmployeeRow {
  id: string;
  name: string;
  email: string | null;
  role: string;
  department: string;
  avatar: string | null;
  description: string | null;
  manager_id: string | null;
  owner_id: string;
  status: EmployeeStatus;
  notes: string | null;
  performance: Record<string, unknown> | null;  // jsonb — formalised later
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface MissionRow {
  id: string;
  title: string;
  description: string | null;
  status: MissionStatus;
  priority: string | null;
  assigned_to: string | null;  // denormalised shortcut, no FK — see DATABASE.md §4
  created_by: string;
  owner_id: string;
  due_date: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface MissionAssignmentRow {
  id: string;
  mission_id: string;
  target_type: AssignmentTargetType;
  manager_id: string | null;
  employee_id: string | null;
  assigned_by_owner: boolean;
  created_at: string;
  updated_at: string;
}

export interface KnowledgeEntryRow {
  id: string;
  title: string;
  content: string;
  layer: KnowledgeLayer;
  mission_id: string | null;
  employee_id: string | null;
  owner_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface ArtifactRow {
  id: string;
  name: string;
  storage_path: string;
  mime_type: string | null;
  size_bytes: number | null;
  checksum: string | null;
  mission_id: string | null;
  employee_id: string | null;
  knowledge_id: string | null;
  owner_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface NotificationRow {
  id: string;
  owner_id: string;
  title: string;
  body: string | null;
  is_read: boolean;
  type: NotificationType;
  actor: NotificationActor;
  entity_type: NotificationEntityType | null;
  entity_id: string | null;
  created_at: string;
  deleted_at: string | null;
}

// ---------------------------------------------------------------------------
// Insert types — shape of data required to insert a new row
// (id, created_at, updated_at are server-generated and omitted)
// ---------------------------------------------------------------------------

export type ProfileInsert = Omit<ProfileRow, "created_at" | "updated_at">;

export type ManagerInsert = Omit<
  ManagerRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type EmployeeInsert = Omit<
  EmployeeRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type MissionInsert = Omit<
  MissionRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type MissionAssignmentInsert = Omit<
  MissionAssignmentRow,
  "id" | "created_at" | "updated_at"
>;

export type KnowledgeEntryInsert = Omit<
  KnowledgeEntryRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type ArtifactInsert = Omit<
  ArtifactRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type NotificationInsert = Omit<NotificationRow, "id" | "created_at" | "deleted_at">;

// ---------------------------------------------------------------------------
// AI Foundation Table Types
// ---------------------------------------------------------------------------

export interface AiConversationRow {
  id: string;
  owner_id: string;
  title: string;
  provider: string;
  model: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface AiMessageRow {
  id: string;
  conversation_id: string;
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  tokens_used: number | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
}

export interface AiUsageLogRow {
  id: string;
  owner_id: string;
  provider: string;
  model: string;
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  latency_ms: number;
  status: "success" | "error";
  created_at: string;
}

export interface KnowledgeChunkRow {
  id: string;
  owner_id: string;
  knowledge_id: string | null;
  artifact_id: string | null;
  chunk_index: number;
  content: string;
  token_count: number | null;
  metadata: Record<string, unknown>;
  embedding: number[];
  created_at: string;
}

// ---------------------------------------------------------------------------
// Update types — all fields optional except id
// ---------------------------------------------------------------------------

export type ManagerUpdate = Partial<Omit<ManagerRow, "id" | "owner_id" | "created_at">>;
export type EmployeeUpdate = Partial<Omit<EmployeeRow, "id" | "owner_id" | "created_at">>;
export type MissionUpdate = Partial<Omit<MissionRow, "id" | "owner_id" | "created_at" | "created_by">>;
export type MissionAssignmentUpdate = Partial<Omit<MissionAssignmentRow, "id" | "mission_id" | "created_at">>;
export type KnowledgeEntryUpdate = Partial<Omit<KnowledgeEntryRow, "id" | "owner_id" | "created_at">>;
export type ArtifactUpdate = Partial<Omit<ArtifactRow, "id" | "owner_id" | "created_at">>;
export type NotificationUpdate = Partial<Omit<NotificationRow, "id" | "owner_id" | "created_at">>;
export type ProfileUpdate = Partial<Omit<ProfileRow, "id" | "created_at">>;

export type AiConversationInsert = Omit<AiConversationRow, "id" | "created_at" | "updated_at" | "deleted_at">;
export type AiMessageInsert = Omit<AiMessageRow, "id" | "created_at">;
export type AiUsageLogInsert = Omit<AiUsageLogRow, "id" | "created_at">;
export type KnowledgeChunkInsert = Omit<KnowledgeChunkRow, "id" | "created_at">;

export type AiConversationUpdate = Partial<Omit<AiConversationRow, "id" | "owner_id" | "created_at">>;
export type AiMessageUpdate = Partial<Omit<AiMessageRow, "id" | "conversation_id" | "created_at">>;
export type AiUsageLogUpdate = Partial<Omit<AiUsageLogRow, "id" | "owner_id" | "created_at">>;
export type KnowledgeChunkUpdate = Partial<Omit<KnowledgeChunkRow, "id" | "owner_id" | "created_at">>;

// ---------------------------------------------------------------------------
// Persistent Memory & Conversation System Types
// ---------------------------------------------------------------------------

export interface ConversationRow {
  id: string;
  owner_id: string;
  title: string;
  summary: string | null;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface ConversationMessageRow {
  id: string;
  conversation_id: string;
  role: string;
  content: string;
  token_count: number | null;
  created_at: string;
}

export interface ConversationSummaryRow {
  id: string;
  conversation_id: string;
  start_message_id: string | null;
  end_message_id: string | null;
  summary_text: string;
  embedding: number[];
  created_at: string;
}

export interface UserMemoryRow {
  id: string;
  owner_id: string;
  organization_id: string | null;
  type: string;
  category: string | null;
  content: string;
  importance: number;
  access_count: number;
  last_accessed_at: string;
  source_conversation_id: string | null;
  embedding: number[];
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export type ConversationInsert = Omit<ConversationRow, "id" | "created_at" | "updated_at" | "deleted_at" | "summary" | "is_archived"> & {
  id?: string;
  title?: string;
  summary?: string | null;
  is_archived?: boolean;
};

export type ConversationMessageInsert = Omit<ConversationMessageRow, "id" | "created_at" | "token_count"> & {
  id?: string;
  token_count?: number | null;
};

export type ConversationSummaryInsert = Omit<ConversationSummaryRow, "id" | "created_at" | "start_message_id" | "end_message_id"> & {
  id?: string;
  start_message_id?: string | null;
  end_message_id?: string | null;
};

export type UserMemoryInsert = Omit<UserMemoryRow, "id" | "created_at" | "updated_at" | "deleted_at" | "access_count" | "last_accessed_at" | "organization_id" | "category"> & {
  id?: string;
  organization_id?: string | null;
  category?: string | null;
  importance?: number;
  access_count?: number;
  last_accessed_at?: string;
};

export type ConversationUpdate = Partial<Omit<ConversationRow, "id" | "owner_id" | "created_at">>;
export type UserMemoryUpdate = Partial<Omit<UserMemoryRow, "id" | "owner_id" | "created_at">>;

// ---------------------------------------------------------------------------
// Product Management CMS Types
// ---------------------------------------------------------------------------

export type ProductStatus = "DRAFT" | "ACTIVE" | "HIDDEN" | "ARCHIVED";

export interface CategoryRow {
  id: string;
  owner_id: string;
  name: string;
  slug: string;
  description: string | null;
  image_url: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface CollectionRow {
  id: string;
  owner_id: string;
  title: string;
  slug: string;
  description: string | null;
  image_url: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface ProductRow {
  id: string;
  owner_id: string;
  category_id: string | null;
  title: string;
  slug: string;
  description: string | null;
  price: number;
  compare_at_price: number | null;
  cost_per_item: number | null;
  sku: string | null;
  barcode: string | null;
  stock_quantity: number;
  low_stock_threshold: number;
  track_inventory: boolean;
  allow_backorder: boolean;
  status: ProductStatus;
  sort_order: number;
  has_variants: boolean;
  tags: string[];
  seo_title: string | null;
  seo_description: string | null;
  canonical_url: string | null;
  og_image_url: string | null;
  robots_meta: string;
  schema_type: string;
  seo_keywords: string[];
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface ProductImageRow {
  id: string;
  product_id: string;
  storage_path: string;
  public_url: string;
  alt_text: string | null;
  caption: string | null;
  position: number;
  is_primary: boolean;
  width: number | null;
  height: number | null;
  created_at: string;
}

export interface VariantOptionRow {
  id: string;
  product_id: string;
  name: string;
  values: string[];
  position: number;
  created_at: string;
}

export interface ProductVariantRow {
  id: string;
  product_id: string;
  title: string;
  options: Record<string, string>;
  price: number;
  compare_at_price: number | null;
  cost_per_item: number | null;
  sku: string | null;
  barcode: string | null;
  stock_quantity: number;
  image_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface InventoryLogRow {
  id: string;
  product_id: string;
  variant_id: string | null;
  before_quantity: number;
  after_quantity: number;
  change_quantity: number;
  reason: string;
  created_by: string | null;
  created_at: string;
}

export interface UrlRedirectRow {
  id: string;
  owner_id: string;
  source_path: string;
  target_path: string;
  status_code: number;
  created_at: string;
}

export type CategoryInsert = Omit<CategoryRow, "id" | "created_at" | "updated_at" | "deleted_at" | "sort_order"> & {
  id?: string;
  sort_order?: number;
};

export type CollectionInsert = Omit<CollectionRow, "id" | "created_at" | "updated_at" | "deleted_at" | "sort_order"> & {
  id?: string;
  sort_order?: number;
};

export type ProductInsert = Omit<ProductRow, "id" | "created_at" | "updated_at" | "deleted_at"> & {
  id?: string;
};

export type ProductUpdate = Partial<Omit<ProductRow, "id" | "owner_id" | "created_at">>;


