/**
 * types/database.ts
 *
 * Supabase database type definitions for Aura OS.
 *
 * Hand-authored from DATABASE.md — the source of truth.
 * When the Supabase CLI becomes available, replace this file with:
 *   supabase gen types typescript --project-id <ref> > types/database.ts
 *
 * Do not edit this file manually once CLI generation is in place.
 */

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

export type MissionStatus =
  | "IDEA"
  | "PLANNING"
  | "APPROVAL"
  | "EXECUTION"
  | "ON_HOLD"
  | "REVIEW"
  | "COMPLETED"
  | "CANCELLED";

export type EmployeeStatus = "ACTIVE" | "IDLE" | "ON_MISSION" | "INACTIVE";

export type KnowledgeLayer = "COMPANY" | "PROJECT" | "EMPLOYEE";

export type AssignmentTargetType = "MANAGER" | "EMPLOYEE";

export type NotificationType =
  | "SYSTEM"
  | "INFO"
  | "SUCCESS"
  | "WARNING"
  | "ERROR"
  | "AI"
  | "AUTOMATION";

export type NotificationActor =
  | "SYSTEM"
  | "OWNER"
  | "MANAGER"
  | "EMPLOYEE"
  | "AI";

export type NotificationEntityType =
  | "MISSION"
  | "MANAGER"
  | "EMPLOYEE"
  | "KNOWLEDGE"
  | "ARTIFACT";

// ---------------------------------------------------------------------------
// Row types — shape of a row returned from Supabase
// ---------------------------------------------------------------------------

export interface ProfileRow {
  id: string;          // uuid — matches auth.users(id)
  full_name: string;
  email: string;
  created_at: string;  // timestamptz returned as ISO string
  updated_at: string;
}

export interface ManagerRow {
  id: string;
  name: string;
  email: string;
  department: string;
  owner_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface EmployeeRow {
  id: string;
  name: string;
  email: string | null;
  role: string;
  department: string;
  avatar: string | null;
  description: string | null;
  manager_id: string | null;
  owner_id: string;
  status: EmployeeStatus;
  notes: string | null;
  performance: Record<string, unknown> | null;  // jsonb — formalised later
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface MissionRow {
  id: string;
  title: string;
  description: string | null;
  status: MissionStatus;
  priority: string | null;
  assigned_to: string | null;  // denormalised shortcut, no FK — see DATABASE.md §4
  created_by: string;
  owner_id: string;
  due_date: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface MissionAssignmentRow {
  id: string;
  mission_id: string;
  target_type: AssignmentTargetType;
  manager_id: string | null;
  employee_id: string | null;
  assigned_by_owner: boolean;
  created_at: string;
  updated_at: string;
}

export interface KnowledgeEntryRow {
  id: string;
  title: string;
  content: string;
  layer: KnowledgeLayer;
  mission_id: string | null;
  employee_id: string | null;
  owner_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface ArtifactRow {
  id: string;
  name: string;
  storage_path: string;
  mime_type: string | null;
  size_bytes: number | null;
  checksum: string | null;
  mission_id: string | null;
  employee_id: string | null;
  knowledge_id: string | null;
  owner_id: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface NotificationRow {
  id: string;
  owner_id: string;
  title: string;
  body: string | null;
  is_read: boolean;
  type: NotificationType;
  actor: NotificationActor;
  entity_type: NotificationEntityType | null;
  entity_id: string | null;
  created_at: string;
  deleted_at: string | null;
}

// ---------------------------------------------------------------------------
// Insert types — shape of data required to insert a new row
// (id, created_at, updated_at are server-generated and omitted)
// ---------------------------------------------------------------------------

export type ProfileInsert = Omit<ProfileRow, "created_at" | "updated_at">;

export type ManagerInsert = Omit<
  ManagerRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type EmployeeInsert = Omit<
  EmployeeRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type MissionInsert = Omit<
  MissionRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type MissionAssignmentInsert = Omit<
  MissionAssignmentRow,
  "id" | "created_at" | "updated_at"
>;

export type KnowledgeEntryInsert = Omit<
  KnowledgeEntryRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type ArtifactInsert = Omit<
  ArtifactRow,
  "id" | "created_at" | "updated_at" | "deleted_at"
>;

export type NotificationInsert = Omit<NotificationRow, "id" | "created_at" | "deleted_at">;

// ---------------------------------------------------------------------------
// Update types — all fields optional except id
// ---------------------------------------------------------------------------

export type ManagerUpdate = Partial<Omit<ManagerRow, "id" | "owner_id" | "created_at">>;
export type EmployeeUpdate = Partial<Omit<EmployeeRow, "id" | "owner_id" | "created_at">>;
export type MissionUpdate = Partial<Omit<MissionRow, "id" | "owner_id" | "created_at" | "created_by">>;
export type MissionAssignmentUpdate = Partial<Omit<MissionAssignmentRow, "id" | "mission_id" | "created_at">>;
export type KnowledgeEntryUpdate = Partial<Omit<KnowledgeEntryRow, "id" | "owner_id" | "created_at">>;
export type ArtifactUpdate = Partial<Omit<ArtifactRow, "id" | "owner_id" | "created_at">>;
export type NotificationUpdate = Partial<Omit<NotificationRow, "id" | "owner_id" | "created_at">>;
export type ProfileUpdate = Partial<Omit<ProfileRow, "id" | "created_at">>;
