/**
 * lib/ai/agent/loop.ts
 *
 * Core Agent Multi-Turn Tool Loop Orchestrator for Aura OS.
 * Manages iterative tool invocation, concurrent execution via Promise.allSettled(),
 * conversation history building, and provider compatibility.
 */

import { formatToolsForOpenAI, parseOpenAIToolCalls } from "../tools/adapters/openai";
import { formatToolsForGemini, parseGeminiToolCalls } from "../tools/adapters/gemini";
import { executeTool } from "../tools/executor";
import type { ToolDefinition, ToolContext, ToolCallRequest, ToolResult } from "../tools/types";
import type { AIMessage } from "../types";

export const DEFAULT_MAX_ITERATIONS = 5;

export type AgentStopReason =
  | "no_tool_calls"
  | "max_iterations_reached"
  | "provider_error";

export interface AgentLoopOptions {
  messages: AIMessage[];
  provider: "openai" | "gemini";
  toolDefinitions: ToolDefinition[];
  context: ToolContext;
  maxIterations?: number;
  providerCallFn: (
    messages: AIMessage[],
    formattedTools?: unknown[]
  ) => Promise<{ text: string; rawResponse?: unknown }>;
}

export interface AgentLoopResult {
  finalText: string;
  updatedMessages: AIMessage[];
  toolCalls: ToolCallRequest[];
  toolResults: ToolResult[];
  iterationCount: number;
  stopReason: AgentStopReason;
  // Backwards compatibility properties
  text?: string;
  hasToolCalls?: boolean;
}

/**
 * Run multi-turn Agent Tool Execution Loop until model generates no tool calls
 * or maxIterations (default: 5) is reached.
 */
export async function runAgentLoop(
  options: AgentLoopOptions
): Promise<AgentLoopResult> {
  const {
    messages,
    provider,
    toolDefinitions,
    context,
    providerCallFn,
    maxIterations = DEFAULT_MAX_ITERATIONS,
  } = options;

  // Format tool definitions using provider adapter once
  const formattedTools =
    provider === "openai"
      ? formatToolsForOpenAI(toolDefinitions)
      : formatToolsForGemini(toolDefinitions);

  const updatedMessages: AIMessage[] = [...messages];
  const accumulatedToolCalls: ToolCallRequest[] = [];
  const accumulatedToolResults: ToolResult[] = [];

  let iterationCount = 0;
  let finalText = "";
  let stopReason: AgentStopReason = "max_iterations_reached";

  while (iterationCount < maxIterations) {
    let response: { text: string; rawResponse?: unknown };

    try {
      response = await providerCallFn(updatedMessages, formattedTools);
      finalText = response.text || finalText;
    } catch (err) {
      console.error(`[AGENT LOOP FATAL ERROR] Turn ${iterationCount + 1}:`, err);
      stopReason = "provider_error";
      if (!finalText) {
        finalText = `⚠️ Error: ${err instanceof Error ? err.message : "Provider call failed."}`;
      }
      break;
    }

    // Detect tool calls from raw provider response
    const turnToolCalls =
      provider === "openai"
        ? parseOpenAIToolCalls(response.rawResponse)
        : parseGeminiToolCalls(response.rawResponse);

    // Stop Condition 1: No tool calls generated by the model
    if (!turnToolCalls || turnToolCalls.length === 0) {
      stopReason = "no_tool_calls";
      // Ensure final assistant message is included in updatedMessages if provided
      if (response.text && response.text.trim().length > 0) {
        const lastMsg = updatedMessages[updatedMessages.length - 1];
        if (!lastMsg || lastMsg.role !== "assistant" || lastMsg.content !== response.text) {
          updatedMessages.push({
            role: "assistant",
            content: response.text,
          });
        }
      }
      break;
    }

    accumulatedToolCalls.push(...turnToolCalls);

    // Milestone 2 — Concurrent Tool Execution
    const settledResults = await Promise.allSettled(
      turnToolCalls.map((call) =>
        executeTool(call.callId, call.toolName, call.arguments, context)
      )
    );

    const turnToolResults: ToolResult[] = settledResults.map((settled, index) => {
      if (settled.status === "fulfilled") {
        return settled.value;
      }
      const call = turnToolCalls[index];
      return {
        callId: call?.callId || `call_${index}`,
        toolName: call?.toolName || "unknown_tool",
        status: "error",
        error: {
          code: "EXECUTION_ERROR",
          message:
            settled.reason instanceof Error ? settled.reason.message : "Unhandled tool failure.",
        },
        executionTimeMs: 0,
      };
    });

    accumulatedToolResults.push(...turnToolResults);

    // Milestone 2 & 4 — Conversation Continuation & History Preservation
    const toolCallSummary = turnToolCalls
      .map((c) => `[Tool Call: ${c.toolName}(${JSON.stringify(c.arguments)})]`)
      .join("\n");

    updatedMessages.push({
      role: "assistant",
      content: response.text
        ? `${response.text.trim()}\n\n${toolCallSummary}`
        : toolCallSummary,
    });

    // Append tool result messages for this turn
    turnToolResults.forEach((res) => {
      updatedMessages.push({
        role: "tool",
        name: res.toolName,
        content: JSON.stringify(
          res.status === "success"
            ? { status: "success", data: res.data }
            : { status: "error", error: res.error }
        ),
      });
    });

    iterationCount++;
  }

  return {
    finalText,
    updatedMessages,
    toolCalls: accumulatedToolCalls,
    toolResults: accumulatedToolResults,
    iterationCount,
    stopReason,
    text: finalText,
    hasToolCalls: accumulatedToolCalls.length > 0,
  };
}
